# Constants
MODEL = "gpt-4o-mini"

# RSS feed list
RSS_FEEDS = [
    "https://buttondown.com/ainews/rss",
    "https://www.engadget.com/rss.xml",
    "https://www.theverge.com/rss/index.xml",
    "https://gizmodo.com/rss",
    "https://kotaku.com/rss",
    "https://www.polygon.com/rss/index.xml",
    "https://hnrss.org/frontpage",
    "https://news.ycombinator.com/rss",
    "http://rss.slashdot.org/Slashdot/slashdot",
    "https://machinelearningmastery.com/blog/feed",
    "http://news.mit.edu/rss/topic/artificial-intelligence2",
    "https://deepmind.com/blog/feed/basic/",
    "https://towardsdatascience.com/feed",
    "https://bair.berkeley.edu/blog/feed.xml",
    "https://www.sciencedaily.com/newsfeeds.htm",
    "https://www.technologyreview.com/feed/",
    "https://www.nature.com/nature/rss/current",
    "https://arxiv.org/list/cs/recent",
    "https://www.kdnuggets.com/feed",
    "https://techcrunch.com/feed/",
]

ALL_RSS_FEEDS = [
    "https://www.engadget.com/rss.xml",
    "https://bleedingcool.com/feed/",
    "https://gizmodo.com/rss",
    "https://kotaku.com/rss",
    "https://www.polygon.com/rss/index.xml",
    "https://www.theverge.com/rss/index.xml",
    "https://news.ycombinator.com/rss",
    "http://www.joystiq.com/rss.xml",
    "http://www.kotaku.com/index.xml",
    "http://www.polygon.com/rss/index.xml",
    "http://feeds.feedburner.com/RockPaperShotgun",
    "http://rss.slashdot.org/Slashdot/slashdot",
    "http://www.slashgear.com/feed/",
    "http://theverge.com/rss/index.xml",
    # "https://hnrss.org/frontpage",
    # "https://buttondown.com/ainews/rss",
    # "https://machinelearningmastery.com/blog/feed",
    # "http://news.mit.edu/rss/topic/artificial-intelligence2",
    # "https://deepmind.com/blog/feed/basic/",
    # "https://towardsdatascience.com/feed",
    # "https://bair.berkeley.edu/blog/feed.xml",
    # "https://www.sciencedaily.com/newsfeeds.htm",
    # "https://www.technologyreview.com/feed/",
    # "https://www.nature.com/nature/rss/current",
    # "https://arxiv.org/list/cs/recent",
    # "https://www.kdnuggets.com/feed",
    # "https://www.popmatters.com/feed",
    # "https://www.theringer.com/rss/pop-culture/index.xml",
    # "https://techcrunch.com/feed/",
    # "https://news.ycombinator.com/rss",
    # "https://api.foxsports.com/v2/content/optimized-rss?partnerKey=MB0Wehpmuj2lUhuRhQaafhBjAJqaPU244mlTDK1i&size=30&tags=fs/mlb",
    # "https://api.foxsports.com/v2/content/optimized-rss?partnerKey=MB0Wehpmuj2lUhuRhQaafhBjAJqaPU244mlTDK1i&size=30&tags=fs/nba",
    # "https://api.foxsports.com/v2/content/optimized-rss?partnerKey=MB0Wehpmuj2lUhuRhQaafhBjAJqaPU244mlTDK1i&size=30&tags=fs/indycar,fs/formula-1",
]

VALID_CATEGORIES = [
    "news",
    "story",
    "press_release",
    "editorial",
    "interview",
    "investigation",
    "product_announcement",
    "review",
    "analysis",
    "opinion",
    "deal/sale",
]

VALID_TAGS = [
    "tech",
    "gaming",
    "mobile",
    "software",
    "hardware",
    "ai",
    "security",
    "business",
    "science",
    "entertainment",
    "shopping",
]
